version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8070:8080"
    depends_on:
      - postgres
    networks:
      subscription-network:
    environment:
      - PROFILE=local-docker
    restart: on-failure
  web-debug:
    build:
      context: .
      dockerfile: Dockerfile-debug
    cap_add:
      - SYS_PTRACE
    ports:
      - "8080:8080"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    environment:
      - PROFILE=local-docker
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - subscription-network

  postgres:
    image: postgres:14.1-alpine
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 20
    ports:
      - '1234:5432'
    volumes:
      - ./postgres-integration-data:/var/lib/postgresql/data
    env_file:
      - environment/local/.env
    networks:
      subscription-network:
volumes:
  postgres-data:
networks:
  subscription-network:
    driver: bridge
